- name: Playbook for packages.yml
  hosts: all
  vars:
    pkgs:
      - php
      - mariadb
  tasks:
    - name: install the packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{pkgs}}"
      when: inventory_hostname in groups['dev'] or inventory_hostname in groups['test'] or inventory_hostname in groups['prod']
      become: true

    - name: install RPM development tool package group
      yum:
        name: "@RPM Development tools"
        state: present
      when: inventory_hostname in groups['dev']
      become: true

    - name: update all packages
      yum:
        name: '*'
        state: latest
      when: inventory_hostname in groups['dev']
      become: true
